language: python

matrix:
  include:
   - env: TOXENV=py26-dj16-sqlite
   - env: TOXENV=py27-dj16-sqlite
   - env: TOXENV=py32-dj16-sqlite
   - env: TOXENV=py33-dj16-sqlite
   - env: TOXENV=py34-dj16-sqlite
   - env: TOXENV=py27-dj17-sqlite
   - env: TOXENV=py32-dj17-sqlite
   - env: TOXENV=py33-dj17-sqlite
   - env: TOXENV=py34-dj17-sqlite
   - env: TOXENV=py26-dj16-postgres
   - env: TOXENV=py27-dj16-postgres
   - env: TOXENV=py32-dj16-postgres
   - env: TOXENV=py33-dj16-postgres
   - env: TOXENV=py34-dj16-postgres
   - env: TOXENV=py27-dj17-postgres
   - env: TOXENV=py32-dj17-postgres
   - env: TOXENV=py33-dj17-postgres
   - env: TOXENV=py34-dj17-postgres

install:
  - pip install tox
  - createdb modelcluster

script:
  tox
