language: python

matrix:
  include:
   - env: TOXENV=py27-dj17-sqlite
   - env: TOXENV=py32-dj17-sqlite
   - env: TOXENV=py33-dj17-sqlite
   - env: TOXENV=py34-dj17-sqlite
   - env: TOXENV=py27-dj18-sqlite
   - env: TOXENV=py32-dj18-sqlite
   - env: TOXENV=py33-dj18-sqlite
   - env: TOXENV=py34-dj18-sqlite
   - env: TOXENV=py27-dj17-postgres
   - env: TOXENV=py32-dj17-postgres
   - env: TOXENV=py33-dj17-postgres
   - env: TOXENV=py34-dj17-postgres
   - env: TOXENV=py27-dj18-postgres
   - env: TOXENV=py32-dj18-postgres
   - env: TOXENV=py33-dj18-postgres
   - env: TOXENV=py34-dj18-postgres

install:
  - pip install tox
  - createdb modelcluster

script:
  tox
